title: <div style="text-align:center;">José Manuel Sánchez Hernández</div>
logo: https://github.com/josh-josh-123/portfolio/blob/main/Jose%20M%20Sanchez%20foto1.png?raw=true
description: Specialist in Product Development & CIB Payment Solutions | Extensive Expertise in Financial Services
#show_downloads: true
theme: jekyll-theme-minimal
